name: flutter_native_image
description: A flutter plugin which uses native iOS/Android to resize, compress or crop
version: 0.0.7
# homepage: https://konseben.dev
# issue_tracker: https://github.com/btastic/flutter_native_image/issues
publish_to: none

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  
  # flutter_native_image_android:
    # path: ../flutter_native_image_android
  flutter_native_image_android:
    git:
      url: https://github.com/avmelnikoff/flutter_native_image.git
      ref: master
      path: flutter_native_image_android/
  
  # flutter_native_image_ios:
  #   path: ../flutter_native_image_ios
  flutter_native_image_ios:
    git:
      url: https://github.com/avmelnikoff/flutter_native_image.git
      ref: master
      path: flutter_native_image_ios/

  # flutter_native_image_aurora:
  #   path: ../flutter_native_image_aurora
  # # flutter_native_image_aurora:
  # #   git:
  # #     url: https://github.com/avmelnikoff/flutter_native_image.git
  # #     ref: master
  # #     path: flutter_native_image_aurora/
  
  # flutter_native_image_platform_interface:
  #   path: ../flutter_native_image_platform_interface
  flutter_native_image_platform_interface:
    git:
      url: https://github.com/avmelnikoff/flutter_native_image.git
      ref: master
      path: flutter_native_image_platform_interface/
  
dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_native_image_android
      ios:
        default_package: flutter_native_image_ios
      # aurora:
      #   default_package: mp_logger_aurora
